### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by s-tikhomirov** [DeepSec-prover/deepsec#11]
Running `make` on Linux Mint 18 I get:

`ocamlopt -I Source/core_library -I Source/subterms -I Source/testing -I Source/parser -I Source/distributed -bin-annot -w Ae str.cmxa unix.cmxa -c Source/core_library/extensions.ml
File "Source/core_library/extensions.ml", line 102, characters 16-17:
Error: Syntax error
Makefile:150: recipe for target 'Source/core_library/extensions.cmx' failed
make: *** [Source/core_library/extensions.cmx] Error 2
`

**Comment by VincentCheval** [comment]
Hello,

You should compile DeepSec with a version of Ocaml at least 4.03
Below this version, it will not compile.

I've added this requirement in the Readme.

**Comment by VincentCheval** [comment]
I've also disabled the "testing interface" in the makefile. This is a mode for developer typically but it hasn't been update to the newest version of DeepSec.

**Comment by s-tikhomirov** [comment]
Yes, this seems to be the problem. I followed the [instructions](https://ocaml.org/docs/install.html) and installed OCaml via apt -- it turned out to be 4.02, [this ppa](https://launchpad.net/~avsm) also has versions up to 4.02. But this is not a DeepSec problem, obviously.

**Comment by VincentCheval** [comment]
You should try with Opam. It works really well. If  you already have Opam installed, try the command 
``opam switch list``
It will give the the available versions and than you can do ``opam switch number_of_the_version_you_want``

(I'm not completely sure about the last one but it's something like this).

**Comment by s-tikhomirov** [comment]
This solves the problem, thank you!
