### ISSUE TITLE
使用install deepsec

### ISSUE THREAD

**Issue by super-logo** [DeepSec-prover/deepsec#20]
when i install deepsec with make, this appears
![2019-01-16 18-11-33](https://user-images.githubusercontent.com/23659183/51242227-69bb3a00-19ba-11e9-9de5-726edc2d9121.png)

**Comment by VincentCheval** [comment]
So sorry, I have missed this message .... I don't know if this issue is still ongoing.

First I think you should not use sudo to compile.
Second, the problem may come from a problem of ocaml version. Try with the latest ocaml version. Don't forget also to do a `make clean` before doing `make`
