### ISSUE TITLE
Path with espace in the executable root path

### ISSUE THREAD

**Issue by victor-yon** [DeepSec-prover/deepsec#27]
For `/media/wip/Workspace/In progress/deepsec/deepsec_api`

With start_run command the error message is : `/bin/sh: 1: /media/wip/Workspace/In: not found`

The run start and stay "in_progress"

**Comment by VincentCheval** [comment]
It should be fixed on 0be52d6a809a5e81cfb0ec2991ab4041c75b71d4

I close the issue but reopen it if you find similar bug.
