### ISSUE TITLE
Trace Equivalence of the same Process

### ISSUE THREAD

**Issue by matzesto** [DeepSec-prover/deepsec#59]
Hi! 

Based on my understanding of Trace Equivalence, I expect that it always hold for any Process `P`, that `P ≈t P`.

However, this seems not to be the case for the following Process, where ProcessA simply signs a message with a fresh key and reveals the according public key.
```
free c.

fun sign/2.
fun pk/1.

reduc verify(sign(m, sk), m, pk(sk)) -> m.

// Sign what is received on Channel c and 
// additionally pass public key back on c
let ProcessA(c) = 
  in(c, msg);
    new sk;
    out(c, (sign(msg, sk), pk(sk))).

// Simply receive and do nothing
let ProcessB(c) = 
  in(c, msg). 

let Process = ProcessA(c) | ProcessB(c).
query trace_equiv(Process, Process).

```
Is my understanding incorrect or is this a bug in DeepSec?

I'm using Version 2.0.0-beta2, Git hash: bd8f43b4fb2c99b75f837336a3c5bf6685d96015

Regard, Matthias

**Comment by VincentCheval** [comment]
Hello,

This is definitely a bug. As you understood, trace equivalence should always hold for `P ≈t P`.

I'll look into it.

Best,
Vincent

**Comment by VincentCheval** [comment]
The bug will be fixed in 2.0.0-beta3. I'm currently running our regression testing so it should be merged in master by evening if everything went well.

**Comment by matzesto** [comment]
Thanks for the fast fix! Unfortunatly, I have a similar (admitted, not very meaningful) example, which still triggers this bug:

```
free c1, c2.

fun sign/2.
fun pk/1.

let ProcessA(c1) = 
  in(c1, msg);
  new sk;
  out(c1, (sign(msg, sk), pk(sk))).

let ProcessB(c1, c2) = 
  in(c2, msg);
  let (x, y, z) = msg in
  out(c1, z).

let ProcessC(c1, c2) =
  in(c2, msg);
  out(c1, msg).

let Process = 
    ProcessA(c2) | !^2 ProcessB(c2, c1) | ProcessC(c2, c1).

query trace_equiv(Process, Process).
```
Tested with:
    Version: 2.0.0-beta3
    Git hash: 55d33bd416db0e0c39a4682373f65da2aaabd67c

Best, 
Matthias

**Comment by VincentCheval** [comment]
Thank again for the bug report 👍 

I will look into it.

**Comment by VincentCheval** [comment]
I found the bug and I'm currently fixing it. Doing some testing.

**Comment by VincentCheval** [comment]
Regression testing was successful so I'm merging. 

Thanks again for your bug report !

Vincent
