### ISSUE TITLE
internal error for reduction rules with non-atomic right-hand sides

### ISSUE THREAD

**Issue by irakoton** [DeepSec-prover/deepsec#63]
The constraint solver returns an internal error when handling a reduction rule for extracting the public-key used to produce a ciphertext:

```
reduc h(f(x,g(y))) -> g(y).
```

where `f` models encryption and `g` public key generation. Attached a minimal example where the error is observable (triggers `Internal Error: [data_structure.ml >> IK.get] Invalid index.`)

[internal_error.txt](https://github.com/DeepSec-prover/deepsec/files/4496421/internal_error.txt)

**Comment by VincentCheval** [comment]
Should be fixed in beta6. Regression testing on fast examples worked. Would probably need to do the heavy examples too. I'm closing the issue for now. We could reopen it if one of the heavy test fails in the future.
