### ISSUE TITLE
internal error with private constants in rewrite rules

### ISSUE THREAD

**Issue by steve-kremer** [DeepSec-prover/deepsec#71]
The following file ([bug.txt](https://github.com/DeepSec-prover/deepsec/files/4648996/bug.txt)) triggers an internal error

`Internal Error: Not_found`

**Note**: the error is not triggered when removing the unused private constant `s`. However this is a minimal example obtained from a more complex example that does use `s`. I am also attaching the initial example ([Passive-ActivityTracking-State.txt](https://github.com/DeepSec-prover/deepsec/files/4648995/Passive-ActivityTracking-State.txt)).

**Comment by VincentCheval** [comment]
It's related to the following enhancement #16 Private constants are not allowed in the right hand side of a rewrite rule but this condition is not tested yet.
