### ISSUE TITLE
bug in skeleton comparison with private channels

### ISSUE THREAD

**Issue by irakoton** [DeepSec-prover/deepsec#73]
There seems to be a bug in the skeleton check of processes with private channels when proving equivalence by session. The problem seems linked with the presence of Bangs (see minimal example where Deepsec fails to detect that !^2 P | P has the same skeleton as P | !^2 P or !^3 P and reports an attack).

[bug.txt](https://github.com/DeepSec-prover/deepsec/files/4893257/bug.txt)

**Comment by VincentCheval** [comment]
Did you try with the ongoing branch that fix previous bug ?

Envoyé de mon iPhone

**Comment by irakoton** [comment]
My bad, the bug does not appear in branch `fix_bug_67_to_72`.
